---
name: CI

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5
      - name: Run yamllint
        uses: frenck/action-yamllint@v1.5.0
